language: node_js
node_js:
  - 12
  - 14
  - 15
sudo: false
before_install:
  - npm i -g npm@latest-6
install:
  # The only reason pnpm is not installed globally
  # is to test that @pnpm/exec can install it
  - npx pnpm install
script:
  - npm test
notifications:
  email: false
