language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
sudo: false
before_install:
  - npm i -g npm
install:
  # The only reason pnpm is not installed globally
  # is to test that @pnpm/exec can install it
  - npx pnpm install
script:
  - npm test
